#!/bin/bash

title() {
	echo -e "\n- $1" | tr '[:lower:]' '[:upper:]'
}

title "docker"
docker compose up -d

symfony server:start -d
npm run dev

title "status proxy"
symfony proxy:status

title "status docker"
docker ps